### ISSUE TITLE
List with countries, estimated nodes and legal status

### ISSUE THREAD

**Issue by danimesq** [hyperboria/todo#3]

**Comment by danimesq** [comment]
Reference: #1

**Comment by kpcyrd** [comment]
There is https://github.com/hyperboria/peers that lists some nodes, the geographical location of all other nodes is unknown.

We are not lawyers, giving legal advice seems like a bad idea. Also, law is non-binary, you can't simplify it into legal vs illegal. There is nothing special about cjdns, unless you are located in a country where mesh networks can get you into trouble there is nothing to worry about. We aren't doing anything that ISPs aren't doing anyway.
